defaults:
  - _self_
  - dataset: rope_cutting
  - model: point_gpt
  - loss_fn: chamfer

batch_size: 128
num_workers: 8
max_epochs: 400
log_every_n_steps: 5

learning_rate: 1e-3
weight_decay: 0.05
use_color: False
