defaults:
  - dataset: modelnet_40
  - embedder: default
  - encoder: default
  - decoder: default
  - masked_encoder: default
  - masked_decoder: default

batch_size: 64
learning_rate: 0.001
num_workers: 4
max_epochs: 50
log_every_n_steps: 5
