defaults:
  - _self_
  - dataset: thread_in_hole
  - model: mae
  - loss_fn: chamfer

batch_size: 128
num_workers: 8
max_epochs: 300
log_every_n_steps: 5

learning_rate: 1e-3
weight_decay: 0.05
use_color: False
