defaults:
  - algo: sac
  - model: sac
  - env: reach
  - optimizer: basic
  - _self_

parallel: True
batch_T: 128
batch_B: 20
max_steps_decorrelate: 0
device: null
runner:
  n_steps: 1e6
  log_interval_steps: 10000
  eval_interval_steps: 20000
eval:
  n_eval_envs: 4
  max_trajectories: 100

tags: null

use_slurm: False
video_path: videos
