defaults:
  - train_sac
  - slurm_local
  - _self_

batch_T: 128
batch_B: 22
use_slurm: True
action_scale: 0.5

# sweep pararmeters
hydra:
  sweeper:
    params:
      algo.ent_coeff: 0.6,0.2
      algo.ent_coeff_lr: 1e-4,5e-5
      optimizer.lr: 1e-4,5e-5
