defaults:
  - _self_
  - algo: sac
  - model: sac
  - env/reach/continuous@env

parallel: True
batch_T: 16
batch_B: 8
max_steps_decorrelate: 0
device: null
runner:
  n_steps: 8388608
  log_interval_steps: 1024
  eval_interval_steps: 20480
eval:
  n_eval_envs: 1
  max_traj_length: 100
  min_trajectories: 4
distribution:
  deterministic_eval_mode: False
