defaults:
  - train_sac
  - platform: horeka
  - _self_

batch_T: 128
batch_B: 20
use_slurm: True

algo:
  batch_size: 256

hydra:
  sweeper:
    params:
      optimizer.lr: 1e-4
      model.transformer_encoder.depth: 3
      algo.ent_coeff_lr: 5e-5, 2e-5
      algo.ent_coeff: 0.3
      algo.batch_size: 128, 256
      algo.replay_ratio: 8, 12
      env: thread_in_hole


