defaults:
  - algo: sac
  - model: sac
  - env: reach
  - optimizer: basic
  - _self_

parallel: True
batch_T: 128
batch_B: 10
max_steps_decorrelate: 0
device: null
runner:
  n_steps: 4194304
  log_interval_steps: 1024
  eval_interval_steps: 10240
eval:
  n_eval_envs: 4
  max_traj_length: 100
  max_trajectories: 4

use_slurm: False
video_path: videos
