defaults:
  - train_sac
  - platform: horeka
  - _self_

batch_T: 128
batch_B: 20
use_slurm: True

hydra:
  sweeper:
    params:
      algo.ent_coeff_lr: 2e-5, 5e-5
      algo.ent_coeff: 0.4
      optimizer.lr: 1e-4, 5e-5
