defaults:
  - finetune_sac
  - platform: horeka
  - _self_

batch_T: 128
batch_B: 20
use_slurm: True

hydra:
  sweeper:
    params:
      algo.ent_coeff_lr: 5e-5
      algo.ent_coeff: 0.4
      optimizer.lr: 1e-4
      scheduler.zero_till_step: 1_600, 3_200, 8_000, 16_000
      scheduler.increase_over_steps: 8_000, 16_000
