defaults:
  - algo: ppo
  - model: aux_ppo_continuous
  - env: reach
  - optimizer: ppo
  - _self_

parallel: True
batch_T: 128
batch_B: 8
reward_clip_min: -5
reward_clip_max: 5
max_steps_decorrelate: 0
device: null
runner:
  n_steps: 8388608
  log_interval_steps: 1024
  eval_interval_steps: 10240
eval:
  n_eval_envs: 4
  max_traj_length: 200
  max_trajectories: 4

video_path: ???
