defaults:
  - train_sac
  - platform: horeka
  - _self_

batch_T: 128
batch_B: 20
use_slurm: True

hydra:
  sweeper:
    params:
      scheduler:
        zero_till_step: 0, 2, 5, 10
        increase_over_steps: 0, 2
