defaults:
  - train_sac
  - slurm_local
  - _self_

batch_T: 128
batch_B: 10
use_slurm: True
action_scale: 1

# sweep pararmeters
hydra:
  sweeper:
    params:
      algo.ent_coeff: 1.0,0.5
      algo.ent_coeff_lr: 1e-4,5e-5
      optimizer.lr: 1e-4,5e-5
