defaults:
  - train_sac
  - platform: horeka
  - _self_

batch_T: 128
batch_B: 20
use_slurm: True

hydra:
  sweeper:
    params:
      algo.ent_coeff_lr: 1e-5, 5e-6
      algo.ent_coeff: 0.03, 0.04, 0.05, 0.06
