defaults:
  - _self_
  - algo: sac
  - model: sac
  - env/reach/continuous@env

parallel: True
batch_T: 128
batch_B: 8
max_steps_decorrelate: 0
device: null
runner:
  n_steps: 4194304
  log_interval_steps: 1024
  # eval_interval_steps: 10240
eval:
  n_eval_envs: 1
  max_traj_length: 200
  min_trajectories: 2
