_target_: pc_rl.builder.build_ppo
discount: 0.99
gae_lambda: 0.95
normalize_advantage: True
epochs: 2
minibatches: 32
ratio_clip: 0.1
value_clipping_mode: "none"
value_loss_coeff: 0.5
entropy_loss_coeff: 0.0
clip_grad_norm: 0.5
learning_rate: 1e-6
learning_rate_scheduler: null
