discount: 0.99
gae_lambda: 0.95
normalize_advantage: True
epochs: 2
minibatches: 64
ratio_clip: 0.1
value_clipping_mode: "none"
value_loss_coeff: 1.
entropy_loss_coeff: 0.01
clip_grad_norm: 1.
learning_rate: 1e-5
learning_rate_scheduler: null
