discount: 0.99
replay_length: 81920
learning_starts: 10240
replay_ratio: 4
batch_size: 96
target_update_tau: 0.005
target_update_interval: 2
ent_coeff: 0.0001
# ent_coeff_lr: 1e-5
clip_grad_norm: 1.e+9
