defaults:
  - pos_embedder: default
  - embedder: default
  - transformer_block: default
  - _self_

masked_encoder:
  _target_: pc_rl.builder.build_masked_encoder
  mask_ratio: 0.6
  mask_type: rand
  transformer_encoder:
    _target_: pc_rl.builder.build_transformer_encoder
    depth: 4

masked_decoder:
  transformer_decoder:
    _target_: pc_rl.builder.build_transformer_decoder
    depth: 4

pi_mlp_head:
  _target_: pc_rl.models.sac.q_and_pi_heads.PiMlpHead
  hidden_sizes: [128, 128]
  hidden_nonlinearity: ReLU

q_mlp_head:
  _target_: pc_rl.models.sac.q_and_pi_heads.QMlpHead
  hidden_sizes: [128, 128]
  hidden_nonlinearity: ReLU


