defaults:
  - pos_embedder : default
  - tokenizer: default
  - transformer_block: default
  - _self_

masked_encoder:
  _target_: pc_rl.builder.build_masked_encoder
  mask_ratio: 0.6
  mask_type: rand
  transformer_encoder:
    _target_: pc_rl.builder.build_transformer_encoder
    depth: 8

masked_decoder:
  transformer_decoder:
    _target_: pc_rl.builder.build_transformer_decoder
    depth: 4
