defaults:
  - transformer_block: default
  - embedder: default
  - pos_embedder: default
  - _self_

masked_encoder:
  _target_: pc_rl.builder.build_masked_encoder
  mask_ratio: 0.6
  mask_type: rand

transformer_encoder:
  _target_: pc_rl.builder.build_transformer_encoder
  depth: 8

transformer_decoder:
  _target_: pc_rl.builder.build_transformer_decoder
  depth: 6

transformer_block:
  dropout: 0.1
