defaults:
  - transformer_block: default
  - tokenizer: point_gpt
  - pos_embedder: default
  - prediction_head: default
  - _self_

gpt_encoder:
  _target_: pc_rl.builder.build_gpt_encoder
  mask_ratio: 0.7
  keep_first_tokens_ratio: 0.15

transformer_encoder:
  _target_: pc_rl.builder.build_transformer_encoder
  depth: 3

transformer_decoder:
  _target_: pc_rl.builder.build_transformer_decoder
  depth: 3

transformer_block:
  dropout: 0.1
