defaults:
  - ppo_base

rl_model:
  _target_: pc_rl.builder.build_continuous_pg_model
  mu_mlp_hidden_sizes: [256, 128]
  mu_mlp_act: tanh
  value_mlp_hidden_sizes: [256, 128]
  value_mlp_act: tanh
  init_log_std: 0.0

