_target_: pc_rl.envs.deflect_spheres.build

action_type: continuous
max_episode_steps: 500
settle_steps: 10
render_mode: headless
observation_type: color_point_cloud
image_shape: [128, 128]
frame_skip: 1
time_step: 0.1
voxel_grid_size: 5.0

num_objects: 5
num_deflect_to_win: 2
min_deflection_distance: 3.0
single_agent: False
camera_reset_noise: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0]

reward_amount_dict:
  action_violated_cartesian_workspace: -0.0
  action_violated_state_limits: -0.0
  tool_collision: -0.0
  distance_to_active_sphere: -1.0
  delta_distance_to_active_sphere: -10.0
  deflection_of_inactive_spheres: -0.005
  deflection_of_active_sphere: 0.0
  delta_deflection_of_active_sphere: 1.0
  done_with_active_sphere: 50.0
  successful_task: 0.0
  rcm_violation_xyz: -0.0
  rcm_violation_rotation: -0.0
