_target_: pc_rl.envs.grasp_lift_and_touch.build

defaults: 
  - base
  - _self_

# base overrides
max_episode_steps: 500
frame_skip: 2
time_step: 0.05
image_shape: [64, 64]

discrete_action_magnitude: 100.0
goal_tolerance: 0.02
start_in_phase: touch
end_in_phase: done
collision_punish_mode: constant
phase_any_rewards:
  collision_cauter_gripper: -0.1
  collision_cauter_gallbladder: -0.1
  collision_cauter_liver: -0.1
  collision_griper_livver: -0.1
  distance_cauter_target: -0.5
  delta_distance_cauter_target: -1.0
  target_visible: 0.0
  gallbladder_is_grasped: 20.0
  new_grasp_on_gallbladder: 10.0
  lost_grasp_on_gallbladder: -10.0
  active_grasping_springs: 0.0
  delta_active_grasping_springs: 0.0
  gripper_pulls_gallbladder_out: 0.005
  overlap_gallbladder_liver: -0.1
  delta_overlap_gallbladder_liver: -0.01
  dynamic_force_on_gallbladder: -0.003
  cauter_action_violated_state_limits: 0.0
  cauter_action_violated_cartesian_workspace: 0.0
  gripper_action_violated_state_limits: 0.0
  gripper_action_violated_cartesian_limits: 0.0
  successful_task: 200.0
  failed_task: 0.0

phase_grasp_rewards:
  distance_gripper_graspable_region: -0.2
  delta_distance_gripper_graspable_region: -10.0

phase_touch_rewards:
  cauter_activation_in_target: 0.0
  cauter_delta_activation_in_target: 1.0
  cauter_touches_target: 0.0
