_target_: pc_rl.envs.mani_skill.build

env_id: Hang-v0
max_episode_steps: 350
image_shape: [64, 64]
control_mode: pd_ee_delta_pose
reward_mode: normalized_dense
observation_type: point_cloud
filter_points_below_z: 1e-3
z_far: 1.5
# z_near: 0.01
# fov: 1.0

