_target_: pc_rl.envs.mani_skill.build

env_id: MoveBucket-v1
max_episode_steps: 200
image_shape: [64, 64]
control_mode: base_pd_joint_vel_arm_pd_joint_delta_pos
reward_mode: normalized_dense
observation_type: point_cloud
filter_points_below_z: 1e-3
voxel_grid_size: 0.03
obs_frame: base
num_frames: 3
continuous_task: False
normalize: True
fov: 1.5
