_target_: pc_rl.envs.mani_skill.build

env_id: PickCube-v0
max_episode_steps: 200
image_shape: [64, 64]
control_mode: pd_ee_delta_pose
reward_mode: normalized_dense
observation_type: point_cloud
filter_points_below_z: 1e-6
voxel_grid_size: 0.01
obs_frame: ee
n_goal_points: 50
normalize: True

