_target_: pc_rl.envs.pick_and_place.build

defaults:
  - base
  - _self_

phase_any_rewards:
  lost_grasp: -30.0
  grasped_torus: 0.0
  gripper_jaw_peg_collision: -0.01
  gripper_jaw_floor_collisions: -0.01
  unstable_deformation: -0.01
  torus_velocity: 0.0
  gripper_velocity: 0.0
  torus_dropped_off_board: 0.0
  action_violated_state_limits: 0.0
  action_violated_cartesian_workspace: 0.0
  successful_task: 50.0

phase_pick_rewards:
  established_grasp: 30.0
  gripper_distance_to_torus_center: 0.0
  delta_gripper_to_torus_center: 0.0
  gripper_distance_to_torus_tracking_points: 0.0
  delta_gripper_distance_to_torus_tracking_points: -10.0
  distance_to_minimum_pick_height: 0.0
  delta_distance_to_minimum_pick_height: -50.0

phase_place_rewards:
  torus_distance_to_active_pegs: 0.0
  delta_torus_distance_to_active_pegs: -100.0


