_target_: pc_rl.envs.reach.build

defaults:
  - base
  - _self_

discrete_action_magnitude: 100.0
distance_to_target_threshold: 0.02
voxel_grid_size: 0.01
use_color: False

reward_amount_dict:
  distance_to_target: -0.01
  # distance_reward: -0.2
  delta_distance_to_target: -0.0
  time_step_cost: -0.0
  workspace_violation: -0.0
  successful_task: 0
  cos_reward: -50.0
create_scene_kwargs:
  show_bounding_boxes: False
  show_remote_center_of_motion: True
