_target_: pc_rl.envs.rope_cutting.build

action_type: continuous
render_mode: headless
observation_type: point_cloud
image_shape: [128, 128]
frame_skip: 1
time_step: 0.1
voxel_grid_size: 5.0
max_episode_steps: 300
settle_steps: 10

num_ropes: 5
num_ropes_to_cut: 1

reward_amount_dict:
  distance_cauter_active_rope: -0.0
  delta_distance_cauter_active_rope: -10.0
  cut_active_rope: 10.0
  cut_inactive_rope: -10.0
  worspace_violation: -0.0
  state_limits_violation: -0.0
  successful_task: 100.0
  failed_task: -20.0
