_target_: pc_rl.envs.rope_cutting.build

defaults:
  - base
  - _self_

max_episode_steps: 300

num_ropes: 5
num_ropes_to_cut: 1

reward_amount_dict:
  distance_cauter_active_rope: -0.0
  delta_distance_cauter_active_rope: -5.0
  cut_active_rope: 5.0
  cut_inactive_rope: -5.0
  worspace_violation: -0.0
  state_limits_violation: -0.0
  successful_task: 10.0
  failed_task: -20.0
