_target_: pc_rl.envs.mani_skill.build

env_id: StackCube-v0
max_episode_steps: 200
image_shape: [96, 96]
control_mode: pd_ee_delta_pose
reward_mode: normalized_dense
observation_type: color_point_cloud
